### ISSUE TITLE
Add failover cache

### ISSUE THREAD

**Issue by arein** [WalletConnect/cerberus#8]
AC:
currently we cache for ~5mins
Should the internal API be down we should have a fallback cache with a ~24h staleness in case the ~5mins are expired and the `/internal` API is down

Implementation suggestion:
when reading from `/internal` API write two records with different TTLs into Redis and if the calls to `/internal` API fails fall back to the second one

**Comment by chris13524** [comment]
Closing in favor of: https://github.com/WalletConnect/cerberus/issues/21
